theme = "hugo-theme-codex" 

defaultContentLanguage = "fr"

title = "Ahmed Tchagnaou"
baseURL = "https://atchagnaou.me"
copyright = "© {year}"

[languages]
[languages.en]
  languageName = "English"

[languages.en.params]
dateFormat = "Jan 2 2006"

# Links to social accounts
github = "https://github.com/Authentic10"
email = "mailto:ahmed.tc@protonmail.com"
linkedin = "https://fr.linkedin.com/in/ahmed-tchagnaou-792a1a167"

# Social icons 
iconOrder = ["GitHub", "Email", "LinkedIn"]
 
[languages.fr] 
  languageName = "Français"

[languages.fr.params]
dateFormat = "2 Jan 2006"


# Links to social accounts
github = "https://github.com/Authentic10"
email = "mailto:ahmed.tc@protonmail.com"
linkedin = "https://fr.linkedin.com/in/ahmed-tchagnaou-792a1a167"

# Social icons 
iconOrder = ["GitHub", "Email", "LinkedIn"]

# Set to true to display page title in table of contents in blog posts.
showPageTitleInTOC = true

# This disables Hugo's default syntax highlighting in favor
# of prismjs.
[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
# English
[[languages.en.menu.main]]
  identifier = "about"
  name = "About"
  title = "About"
  url = "/"

[[languages.en.menu.main]]
  identifier = "work"
  name = "Work"
  title = "Work"
  url = "/work"

[[languages.en.menu.main]]
  identifier = "resume"
  name = "Resume"
  title = "Resume"
  url = "/resume"

# French
[[languages.fr.menu.main]]
  identifier = "about"
  name = "A propos"
  title = "A propos"
  url = "/"

[[languages.fr.menu.main]]
  identifier = "work"
  name = "Projets"
  title = "Projets"
  url = "/work"

[[languages.fr.menu.main]]
  identifier = "resume"
  name = "CV"
  title = "CV"
  url = "/resume"



