baseURL = 'https://atchagnaou.me/'
languageCode = 'fr-fr'
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = false
title = 'Ahmed Tchagnaou'
theme = "hugo-noir"
googleAnalytics = "G-EHPWT04HPB"

# URL handling
relativeURLs = true
canonifyURLs = true

# Taxonomy configuration
[taxonomies]
  category = "categories"
  tag = "tags"


[params]
name = "Ahmed Tchagnaou"
location = "France"
description = "Ingénieur de données. Data Engineering · IA/ML"
profile_image = "/images/profile.jpg"
github = "https://github.com/Authentic10"
github_username = "Authentic10"
email = "ahmed@atchagnaou.me"
linkedin = "https://www.linkedin.com/in/atchagnaou/"
linkedin_username = "atchagnaou"



[languages]
  [languages.fr]
    languageName = "Français"
    title = "Ahmed Tchagnaou"
    weight = 1
    [languages.fr.menu]
      [[languages.fr.menu.main]]
        name = "A propos"
        pageRef = "/about"
        weight = 1
      [[languages.fr.menu.main]]
        name = "Expérience"
        pageRef = "/experience"
        weight = 2
      [[languages.fr.menu.main]]
        name = "Projets"
        pageRef = "/projects"
        weight = 3
      [[languages.fr.menu.main]]
        name = "Blog"
        pageRef = "/blogs"
        weight = 4
      [[languages.fr.menu.main]]
        name = "Contact"
        pageRef = "/contact"
        weight = 5

  [languages.en]
    languageName = "English"
    title = "Ahmed Tchagnaou"
    weight = 2
    contentDir = "content/en"
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "About"
        pageRef = "/about"
        weight = 1
      [[languages.en.menu.main]]
        name = "Experience"
        pageRef = "/experience"
        weight = 2
      [[languages.en.menu.main]]
        name = "Projects"
        pageRef = "/projects"
        weight = 3
      [[languages.en.menu.main]]
        name = "Blog"
        pageRef = "/blogs"
        weight = 4
      [[languages.en.menu.main]]
        name = "Contact"
        pageRef = "/contact"
        weight = 5
